# -*- coding: utf-8 -*-
"""Simple ML Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUG8u8eU5apsrtmwP4VfXFdmIPktwXgK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv(r"/content/sample_data/california_housing_test.csv")

data

data.info()

from sklearn.model_selection import train_test_split

x = data.drop(['median_house_value'], axis = 1)
y = data['median_house_value']

x_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

train_data = x_train.join(y_train)

train_data

plt.figure(figsize = (20, 8))
train_data.hist()

plt.figure(figsize = (15, 8))
sns.heatmap(train_data.corr(), annot = True, cmap = 'YlGnBu')

train_data['total_rooms'] = np.log(train_data['total_rooms'] + 1)
train_data['total_bedrooms'] = np.log(train_data['total_bedrooms'] + 1)
train_data['population'] = np.log(train_data['population'] + 1)
train_data['households'] = np.log(train_data['households'] + 1)

plt.figure(figsize = (15, 8))
train_data.hist()

plt.figure(figsize = (15, 8))
sns.scatterplot(x = "latitude", y = "longitude", data = train_data, hue = "median_house_value", palette = 'coolwarm')

train_data['bedroom_ratio'] = train_data['total_bedrooms'] / train_data['total_rooms']
train_data['household_rooms'] = train_data['total_rooms'] / train_data['households']

plt.figure(figsize = (15, 8))
sns.heatmap(train_data.corr(), annot = True, cmap = 'YlGnBu')

from sklearn.linear_model import LinearRegression

X_train, y_train = train_data.drop('median_house_value', axis = 1), train_data['median_house_value']

reg = LinearRegression()

reg.fit(x_train, y_train)

test_data = x_train.join(y_train)

test_data['total_rooms'] = np.log(train_data['total_rooms'] + 1)
test_data['total_bedrooms'] = np.log(train_data['total_bedrooms'] + 1)
test_data['population'] = np.log(train_data['population'] + 1)
test_data['households'] = np.log(train_data['households'] + 1)

test_data['bedroom_ratio'] = train_data['total_bedrooms'] / train_data['total_rooms']
test_data['household_rooms'] = train_data['total_rooms'] / train_data['households']

X_test, y_test = test_data.drop('median_house_value', axis = 1), test_data['median_house_value']

reg.score(X_test, y_test)